### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wildernessfamily** [DoubleBastionAdmin/sms-relentless#1]
Hi, I came across your extension in my NextCloud instance. I have two questions.
1. Is the code open source here on Github or Gitlab where you can contribute?
2. Any chance of adding Twilio?
I'm a developer and have added Twilio to many extensions and programs I write. Thought maybe take a look at the code and possibly add it.

**Comment by DoubleBastionAdmin** [comment]
Hi,

1. SMS Relentless is free and open source software, published under the AGPL v3.0 license, like Nextcloud. The code is not hosted on GitHub, but on GitList, on our server, [here](https://git.doublebastion.com/sms-relentless/tree/develop/). We do accept code contributions from anyone who submits [this form](https://git.doublebastion.com/sms-relentless/pullrequests/develop), on the condition that their code contributions add useful and desirable features to the application.

2.  We don't plan to add Twilio to the list of SMS services providers to which the application can connect, because the main goal of SMS Relentless is to provide SMS sending/receiving capabilities inside Nextcloud **at the best quality and lowest prices** possible today. This is why we chose only Telnyx and Plivo as providers, and not other companies. We do not question the quality of the SMS services offered by Twilio, but their prices for inbound/outbound SMS messages ($0.0075 both for inbound and outbound) listed [here](https://www.twilio.com/sms/pricing/us) are clearly much higher then the corresponding prices of Telnyx ($0.0025 for outbound and free for inbound) listed [here](https://telnyx.com/pricing/messaging), or Plivo ($0.0050 for outbound and free for inbound), listed [here](https://www.plivo.com/pricing/). Indeed, the prices of inbound/outbound SMS messages are not the only thing that has to be taken into account when choosing a provider, but the reality is that both Telnyx and Plivo offer a powerful API, with a lot of features and good technical support.

**Comment by wildernessfamily** [comment]
Hi,
Thank you so much for responding.
I have never worked with Telnyx and Plivo. I just looked up both of those companies and they look fantastic.
I'm going to do a bit more research and may move over from Twilio to one of them next week.
Since I have never worked with these companies and you may have a bit more experience with these two is there one you prefer over the other? I have a lot of clients that use Asterisk utilizing SIP. At first glance, Telnyx really jumps out to me as the one to try first. Their API docs seem to be very detailed and easy to read and access. But, wanted to see if you had any input on the two companies.
Thanks again for taking the time to respond and providing the info. :)
David.

**Comment by DoubleBastionAdmin** [comment]
I searched a lot for the SIP services with the highest quality, at the lowest price possible. I have direct experience with Telnyx, Localphone, Plivo, Phaxio, Nexmo/Vonage, Bandwidth and indirect experience with Voip.ms, Callcentric, Twilio, Flowroute, etc. The providers that have their own communications infrastructure tend to offer much lower prices than those using third party services. My conclusions are the following: 

- the best two providers for voice services are **Telnyx** and **Localphone** (Localphone can be used only when connecting to it via Asterisk and doesn't offer many features, but what they offer is top quality, reliable and cheap).
- the best two providers for SMS services are **Telnyx** and **Plivo**.
- the best two providers for FAX services are **Telnyx** and **Phaxio**.

I have to point out that I'm not affiliated in any way with the companies mentioned above. These companies are not necessarily the most visible online because there are big competitors with more aggressive advertising. These competitors offer basically the same services but at much higher prices.

So, if you choose Telnyx for SMS services, you won't go wrong. They have excellent prices, good deliverability, a powerful API, detailed documentation and good technical support, although clearly not perfect. You can connect a web application like [SMS Relentless](https://www.doublebastion.com/sms-relentless/) to your Telnyx account and send/receive very cheap SMS messages. If you have a voice enabled phone number in your Telnyx account, you can connect a WebRTC client, like [SIP Trip Phone](https://www.doublebastion.com/sip-trip-phone/) directly to it and make/receive phone calls with $0.0020 per minute in the US. (I wrote a short guide on how to connect SIP Trip Phone directly to a Telnyx account in the last post on [this thread](https://help.nextcloud.com/t/fund-raising-for-sip-client-app/18439/38). You can also connect SIP Trip Phone to Telnyx via Asterisk, to benefit from all the advanced PBX features offered by Asterisk. Also Telnyx offers FAX enabled phone numbers and their API can be used to send/receive faxes from a web application. They introduced this function quite recently and I haven't implemented it in an application. Instead, I developed [Pax Fax](https://www.doublebastion.com/pax-fax/), which uses Phaxio as FAX over IP provider: still cheap and very reliable.

Plivo is also good for SMS services, but for their voice services they don't allow connections from the external Asterisk server of all of their clients. As a Plivo client, you have to request access in order to connect your Asterisk server to your Plivo account. On the other hand, Telnyx and Localphone allow all their customers to connect their Asterisk servers to their Telnyx/Localphone accounts.

If you ever need a fully featured browser phone for audio/video calling, video conferencing and encrypted text messaging, you can use [Roundpin](https://www.doublebastion.com/roundpin/). I tested it recently and it can be connected to Telnyx both directly and via Asterisk. However, for video calls, conferences and text messaging, you will need Asterisk. It's all free and open source software.

**Comment by wildernessfamily** [comment]
A Telnyx sales agent reached out to me. Very impressed. Their API docs are fantastic. 
I just install the PaxFax extension. I didn't think I was ever going to need fax again. But, I needed reports from the Florida DMV for a project and they still fax. Then I saw you developed. You have done an amazing job. I signed up with Phaxio to use with the extension. I looked over their API guide and was very pleased. I don't get a lot of requests for Fax API but if I do I know who to use. Thanks for the info on Phaxio.

For Sip Softphones I use to use Bria but switched to Zoiper many, many years ago maybe even a decade ago. Overall, love Zoiper but I will definitely check out Roundpin. That looks pretty awesome.

Thanks for all the info!

**Comment by DoubleBastionAdmin** [comment]
Thank you. I'm glad to hear you installed Pax Fax. Many institutions, like the IRS and companies in the health sector still use fax a lot because it is considered more private and secure than emails. Please don't hesitate to post any questions or issues here if you have any problems with the mentioned apps.

**Comment by DoubleBastionAdmin** [comment]
@wildernessfamily 
Thank you for your appreciative words posted on the Pax Fax page, in the Nextcloud app store . Please note that Double Bastion is the developer of Pax Fax and not Damon Hart, as you mentioned in the review. Damon Hart made just a small contribution and has no connection with Double Bastion. Please consider changing the text of the review by replacing the 3 occurrences of 'Damon Hart' or 'Damon' with 'the developer' or 'the developer of Pax Fax'. Thank you.
