### ISSUE TITLE
PHP  error twillo webhook failling to added recieved text messages from twillo.

### ISSUE THREAD

**Issue by technoman555** [DoubleBastionAdmin/sms-relentless#5]
after adding the app to my nextcloud instance and adding my Twillo information. I can successfully send text messages. but when twillo fires the webhook on recived messages the the following error is logged repeatedly.
 
{"reqId":"noqqlbMPeHbOOGproonQ","level":3,"time":"2023-11-16T17:23:03+00:00","remoteAddr":"*********","user":"--","app":"PHP","method":"POST","url":"/apps/sms_relentless/api/recsmstwil?twilrecparam=GY2iiQo9YH2yvP3mWqEEMk5mQ1dzmvtKDo4&twilrecparam=GY2iiQo9YH2yvP3mWqEEMk5mQ1dzmvtKDo4","message":"Trying to access array offset on value of type bool at /var/www/html/custom_apps/sms_relentless/lib/Service/SmsrelentlessService.php#3890","userAgent":"TwilioProxy/1.1","version":"27.1.3.2","data":{"app":"PHP"},"id":"65564ffadbb10"}

**Comment by DoubleBastionAdmin** [comment]
The webhook URL for receiving messages that you posted above is:
```
"/apps/sms_relentless/api/recsmstwil?twilrecparam=GY2iiQo9YH2yvP3mWqEEMk5mQ1dzmvtKDo4&twilrecparam=GY2iiQo9YH2yvP3mWqEEMk5mQ1dzmvtKDo4"
```
Why does `twilrecparam=` appear twice in your URL ? It should appear only once, like this:
```
"/apps/sms_relentless/api/recsmstwil?twilrecparam=GY2iiQo9YH2yvP3mWqEEMk5mQ1dzmvtKDo4"
```
Please go to the admin settings page of 'SMS Relentless' and press again the button 'Generate new webhook URL for incoming SMS/MMS', then, if the new webhook URL contains only one `twilrecparam`, as it is normal, press the 'Save' button at the bottom of the settings page, then copy the newly generated URL and enter it in your Twilio account, as described on the settings page.

Do you have the latest stable Nextcloud version (27.1.3) and the latest version of 'SMS Relentless' (1.3.1) ?

Also, why have you installed 'SMS Relentless' separately, in the ` /var/www/html/custom_apps/` directory, and not like any other app, in the `/var/www/html/nextcloud/apps` directory. Since you installed it separately, do you have [correct](https://docs.nextcloud.com/server/latest/admin_manual/apps_management.html#using-custom-app-directories) settings for using a custom app directory, in your `config.php` file ? Is the `/var/www/html/custom_apps/` directory and its subdirectories owned by the web server user `www-data` ?

**Comment by technoman555** [comment]
this is on nextcloud aio so if it is using a different app directory I do not know as. I have only office installed and that works perfectly fine with no errors.  

i fixed the webhook duplicate url error:

`{"reqId":"mqq41jRDLahg3RGBOd95","level":3,"time":"2023-11-16T23:16:28+00:00","remoteAddr":"35.153.131.156","user":"--","app":"PHP","method":"POST","url":"/apps/sms_relentless/api/recsmstwil?twilrecparam=GY2iiQo9YH2yvP3mWqEEMk5mQ1dzmvtKDo4","message":"Trying to access array offset on value of type bool at /var/www/html/custom_apps/sms_relentless/lib/Service/SmsrelentlessService.php#3818","userAgent":"TwilioProxy/1.1","version":"27.1.3.2","data":{"app":"PHP"},"id":"6556a30c611da"} `

**Comment by DoubleBastionAdmin** [comment]
What do you mean by **Nextcloud aio** ? Do you run Nextcloud in Docker or Snap ? Or is Nextcloud installed directly on the server ?

**Comment by technoman555** [comment]
running it in docker this is the version im running [https://github.com/nextcloud/all-in-one](url)

**Comment by DoubleBastionAdmin** [comment]
SMS Relentless wasn't tested on Nextcloud inside Docker. If you want to make sure that it runs as expected, you have to install Nextcloud directly on the server and then install SMS Relentless, like any other app. SMS Relentless should be in the `apps` directory located in the Nextcloud root directory, and not in the `custom_apps` directory, outside the Nextcloud root directory, as it seems it is in your setup. The Docker image of Nextcloud has some odd settings since it installs apps directly into a `custom_apps` directory without asking the user. The location is important. [Here](https://www.doublebastion.com/install-nextcloud/) we explain in detail how to install Nextcloud, SMS Relentless, and other useful apps directly on the server.
