### ISSUE TITLE
Can't view incoming texts

### ISSUE THREAD

**Issue by johncarterofmars** [DoubleBastionAdmin/sms-relentless#6]
We have an NC deployment using SMS Relentless with Telnyx. The admin user can send and receive without issue. Messages are viewable in both the sent and received. However, users can only view the ones they send, not the ones received. Each user has generated and saved the webhooks. Each user will get an alert that a text has been received, but only the admin user can view it. 

Each user has been given rights to SMS Relentless and can send messages. Any advice as to how to fix the viewing of messages? Thank you.

**Comment by DoubleBastionAdmin** [comment]
@johncarterofmars Are you using the Nextcloud All-In-One (AIO) Docker installation of Nextcloud ?

**Comment by johncarterofmars** [comment]
Yes we are.

**Comment by DoubleBastionAdmin** [comment]
We have just tested SMS Relentless again, and it works as expected. A non-admin user can see both incoming and outgoing messages on/from the phone number shared with him by an admin. Therefore, the issue comes from your setup. In our [Documentation](https://www.doublebastion.com/install-nextcloud/) we explain in detail how to install Nextcloud directly on the server. We even state that "we strongly advice against installing Nextcloud by using the Nextcloud All-in-One (AIO) Docker image". This automated installation does some peculiar things, like automatically creating the directory `custom_apps` in the Nextcloud root directory, and installing all the apps that are not developed by Nextcloud, like SMS Relentless, into that `custom_apps` directory instead of the `apps` directory located in the root directory. This has the efffect of breaking the webhook URLs and causing other problems. We also explain on the mentioned page that if you installed the Nextcloud All-in-One version, you should move the app to the `apps` directory and comment out the `<icon>../img/sms_relentless.svg</icon>` line from the `sms_relentless/appinfo/info.xml` file. (Then regenerate and save all the webhook URLs on the admin's and non-admin's settings page).

Do you see any data logged in the Nextcloud log at the moment you send the message to a non-admin user ? Please post a sample of the 2 webhook URLs for Telnyx, for a non-admin user, as they are generated when clicking the respective buttons. Replace the real domain name and the real alphanumeric parameters with placeholders, for security reasons.

**Comment by DoubleBastionAdmin** [comment]
@johncarterofmars Have you run a test with the app moved to the `apps` directory ?

**Comment by johncarterofmars** [comment]
Affirmative. The issue persists. I am sorry that I didn't see your install guide from the Nextcloud app store. We saw the app there and installed it. When it worked under admin, we didn't think anything further than that until we tested with users. 
I moved the folder from custom_apps to apps, regenerated the webhook URLs, updated the webhook URL at Telnyx, and saved everything. However, the issue is the same. I also commented out the icon like and I am guessing that caused the icon to be unavailable now in the nav menu of Nextcloud. 
![ksnip_20240113-163248](https://github.com/DoubleBastionAdmin/sms-relentless/assets/17039716/61c73eda-c49c-4dfa-be4a-fe1850db9819)
Also, I wanted to make sure our setup is clear. We have 1 single Telnyx number that is shared by every user, not one number user, in case I didn't make that clear. 
I checked the Nextcloud log and there is nothing listed for SMS Relentless
Example webhook - 
`https://sub.domain.com/apps/sms_relentless/api/recsmstel?telrecparam=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Please let me know if you need anything else.

**Comment by DoubleBastionAdmin** [comment]
1. How did you share the phone number with the non-admin users ? You entered their names in the "Users Allowed" text box or you added the users to a group and then entered that group in the "Groups Allowed" text box, in the "Telnyx Settings" section ?

2. Do you have the phone number restricted to a specific user or to all the users, in the section "Restrict access to the following phone numbers" at the bottom of the admin settings page ? If not, what happens when you restrict that single phone number to the group to which all the non-admin users belong. Can they see the received messages ?

3.  Is there any error or warning in the Nextcloud log or in the browser console when a non-admin user clicks the "Received Messages" button ?

**Comment by johncarterofmars** [comment]
We got it working, thank you. We had given the group and all users access under the Telnyx section but in the Restrict access, we didn't have any group or user. I added them in and it worked. I appreciate your help.
